name = "rok-manager"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "rok-manager-db"
database_id = "d3367481-7fa5-4e28-8139-d097d32c7bca"
